name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v5
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run all